/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
    VarBottomNavigation: typeof import('@varlet/ui')['_BottomNavigationComponent']
    VarBottomNavigationItem: typeof import('@varlet/ui')['_BottomNavigationItemComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCell: typeof import('@varlet/ui')['_CellComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarMenu: typeof import('@varlet/ui')['_MenuComponent']
  }
}
